name: FakeSnow
version: '${version}'
main: com.jacky8399.fakesnow.FakeSnow
api-version: 1.21
load: POSTWORLD
depend:
  - ProtocolLib
softdepend:
  - WorldGuard
authors: [ jacky8399 ]
description: Clientside snow effects
commands:
  fakesnow:
    permission: fakesnow.admin

permissions:
  fakesnow.admin:
    default: op